import type { Metadata } from "next";
import { Merriweather, Source_Code_Pro } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import Navbar from "./_components/nav/Navbar";
import ClientProviders from "./ClientProviders";
import Footer from "./_components/home/Footer";

export const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
});

export const merriweather = Merriweather({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Next Chapter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourceCodePro.className} antialiased`}>
        <ClientProviders>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <div className="flex-1 flex flex-col">{children}</div>
          </div>
          <Footer />
          <Toaster closeButton richColors position="top-center" />
        </ClientProviders>
      </body>
    </html>
  );
}
